# Ditch sudo and use containers.
# @link http://docs.travis-ci.com/user/migrating-from-legacy/#Why-migrate-to-container-based-infrastructure%3F
# @link http://docs.travis-ci.com/user/workers/container-based-infrastructure/#Routing-your-build-to-container-based-infrastructure
sudo: false
language: php

notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    secure: AWChP4VNY2AKReOeq2Wr6UNvZh4XX4fBuBY7LvYSaf1DJ9UuuOjGKVo+tFnVat5Aip9IwNlimQZLsfgRSa8UanI1AdA2PnMLGbwd2LiDxlYeFdrVw2dEYVRw6MwFX25tkOosDwMi4CrChRBE4KxB+QhDTX0jZKGVK2zwTZCJ7ig=

cache:
  directories:
  - vendor
  - "$HOME/.composer/cache"

matrix:
  include:
    # Run trunk in nightly and PHP 7.2
    - php: nightly
      env: WP_VERSION=trunk
    - php: 7.2
      env: WP_VERSION=trunk
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=1 # For PHP 5.6 also run Multisite
    - php: 5.5
      env: WP_VERSION=latest
    - php: 5.4
      env: WP_VERSION=latest
    - php: 5.3
      env: WP_VERSION=latest WP_MULTISITE=1 # For PHP 5.3 also run Multisite
      dist: precise
  allow_failures:
    - php: nightly
  fast_finish: true

install:
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:2} == "5." ]] || [[ $TRAVIS_PHP_VERSION == 7.0 ]]; then
      bash bin/install-wp-test-tools.sh
    else
      # Run composer install only for PHP 7.1 or above. The dependencies are not compatible with PHP 5.x
      composer install
    fi

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ $TRAVIS_PHP_VERSION != 7.1 ]]; then
      # Disable x-debug to increase performance. x-debug is enabled only for PHP 7.1 to run code-coverage reports.
      if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
        phpenv config-rm xdebug.ini
      else
        echo "xdebug.ini does not exist"
      fi
    fi
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      composer global require "phpunit/phpunit=4.8.*|5.7.*"
    fi

script:
  - |
    if [[ $TRAVIS_PHP_VERSION == 7.1 ]]; then
      # Validate composer.json file
      composer validate --no-check-all --strict

      # Run code coverage for PHP 7.1 alone
      npm run test:cover-coverage
      npm run phpcs
    else
      phpunit

      if [[ ! -z "$WP_MULTISITE" ]] ; then
        WP_MULTISITE=1 phpunit
      fi
    fi

after_script:
  - |
    if [[ $TRAVIS_PHP_VERSION == 7.1 ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover code-coverage/bulk-move.clover
    fi
